spring:
  datasource:
    username: root
    password: 1001101
    url: jdbc:mysql://localhost:3306/tjpu?serverTimezone=GMT%2B8
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#debug: true

